/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAdapterPyth,
  IAdapterPythInterface,
} from "../../../contracts/oracle/IAdapterPyth";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "priceFeedId",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    name: "latestPrice",
    outputs: [
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAdapterPyth__factory {
  static readonly abi = _abi;
  static createInterface(): IAdapterPythInterface {
    return new utils.Interface(_abi) as IAdapterPythInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAdapterPyth {
    return new Contract(address, _abi, signerOrProvider) as IAdapterPyth;
  }
}
