/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISupraSValueFeed,
  ISupraSValueFeedInterface,
} from "../../../contracts/oracle/ISupraSValueFeed";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "_pairIndex",
        type: "uint64",
      },
    ],
    name: "getSvalue",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64[]",
        name: "_pairIndexes",
        type: "uint64[]",
      },
    ],
    name: "getSvalues",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
      {
        internalType: "bool[]",
        name: "",
        type: "bool[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISupraSValueFeed__factory {
  static readonly abi = _abi;
  static createInterface(): ISupraSValueFeedInterface {
    return new utils.Interface(_abi) as ISupraSValueFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISupraSValueFeed {
    return new Contract(address, _abi, signerOrProvider) as ISupraSValueFeed;
  }
}
