/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace Position {
  export type AddressesStruct = {
    account: PromiseOrValue<string>;
    market: PromiseOrValue<string>;
    collateralToken: PromiseOrValue<string>;
  };

  export type AddressesStructOutput = [string, string, string] & {
    account: string;
    market: string;
    collateralToken: string;
  };

  export type NumbersStruct = {
    sizeInUsd: PromiseOrValue<BigNumberish>;
    sizeInTokens: PromiseOrValue<BigNumberish>;
    collateralAmount: PromiseOrValue<BigNumberish>;
    borrowingFactor: PromiseOrValue<BigNumberish>;
    fundingFeeAmountPerSize: PromiseOrValue<BigNumberish>;
    longTokenClaimableFundingAmountPerSize: PromiseOrValue<BigNumberish>;
    shortTokenClaimableFundingAmountPerSize: PromiseOrValue<BigNumberish>;
    increasedAtBlock: PromiseOrValue<BigNumberish>;
    decreasedAtBlock: PromiseOrValue<BigNumberish>;
  };

  export type NumbersStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    sizeInUsd: BigNumber;
    sizeInTokens: BigNumber;
    collateralAmount: BigNumber;
    borrowingFactor: BigNumber;
    fundingFeeAmountPerSize: BigNumber;
    longTokenClaimableFundingAmountPerSize: BigNumber;
    shortTokenClaimableFundingAmountPerSize: BigNumber;
    increasedAtBlock: BigNumber;
    decreasedAtBlock: BigNumber;
  };

  export type FlagsStruct = { isLong: PromiseOrValue<boolean> };

  export type FlagsStructOutput = [boolean] & { isLong: boolean };

  export type PropsStruct = {
    addresses: Position.AddressesStruct;
    numbers: Position.NumbersStruct;
    flags: Position.FlagsStruct;
  };

  export type PropsStructOutput = [
    Position.AddressesStructOutput,
    Position.NumbersStructOutput,
    Position.FlagsStructOutput
  ] & {
    addresses: Position.AddressesStructOutput;
    numbers: Position.NumbersStructOutput;
    flags: Position.FlagsStructOutput;
  };
}

export declare namespace Market {
  export type PropsStruct = {
    marketToken: PromiseOrValue<string>;
    indexToken: PromiseOrValue<string>;
    longToken: PromiseOrValue<string>;
    shortToken: PromiseOrValue<string>;
  };

  export type PropsStructOutput = [string, string, string, string] & {
    marketToken: string;
    indexToken: string;
    longToken: string;
    shortToken: string;
  };
}

export declare namespace Price {
  export type PropsStruct = {
    min: PromiseOrValue<BigNumberish>;
    max: PromiseOrValue<BigNumberish>;
  };

  export type PropsStructOutput = [BigNumber, BigNumber] & {
    min: BigNumber;
    max: BigNumber;
  };
}

export declare namespace MarketUtils {
  export type MarketPricesStruct = {
    indexTokenPrice: Price.PropsStruct;
    longTokenPrice: Price.PropsStruct;
    shortTokenPrice: Price.PropsStruct;
  };

  export type MarketPricesStructOutput = [
    Price.PropsStructOutput,
    Price.PropsStructOutput,
    Price.PropsStructOutput
  ] & {
    indexTokenPrice: Price.PropsStructOutput;
    longTokenPrice: Price.PropsStructOutput;
    shortTokenPrice: Price.PropsStructOutput;
  };
}

export declare namespace PositionUtils {
  export type IsPositionLiquidatableInfoStruct = {
    remainingCollateralUsd: PromiseOrValue<BigNumberish>;
    minCollateralUsd: PromiseOrValue<BigNumberish>;
    minCollateralUsdForLeverage: PromiseOrValue<BigNumberish>;
  };

  export type IsPositionLiquidatableInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    remainingCollateralUsd: BigNumber;
    minCollateralUsd: BigNumber;
    minCollateralUsdForLeverage: BigNumber;
  };
}

export interface PositionManagerInterface extends utils.Interface {
  functions: {
    "isPositionLiquidatable(address,address,((address,address,address),(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256),(bool)),(address,address,address,address),((uint256,uint256),(uint256,uint256),(uint256,uint256)),bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "isPositionLiquidatable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isPositionLiquidatable",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      Position.PropsStruct,
      Market.PropsStruct,
      MarketUtils.MarketPricesStruct,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "isPositionLiquidatable",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PositionManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PositionManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isPositionLiquidatable(
      dataStore: PromiseOrValue<string>,
      referralStorage: PromiseOrValue<string>,
      position: Position.PropsStruct,
      market: Market.PropsStruct,
      prices: MarketUtils.MarketPricesStruct,
      shouldValidateMinCollateralUsd: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, PositionUtils.IsPositionLiquidatableInfoStructOutput]
    >;
  };

  isPositionLiquidatable(
    dataStore: PromiseOrValue<string>,
    referralStorage: PromiseOrValue<string>,
    position: Position.PropsStruct,
    market: Market.PropsStruct,
    prices: MarketUtils.MarketPricesStruct,
    shouldValidateMinCollateralUsd: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, PositionUtils.IsPositionLiquidatableInfoStructOutput]
  >;

  callStatic: {
    isPositionLiquidatable(
      dataStore: PromiseOrValue<string>,
      referralStorage: PromiseOrValue<string>,
      position: Position.PropsStruct,
      market: Market.PropsStruct,
      prices: MarketUtils.MarketPricesStruct,
      shouldValidateMinCollateralUsd: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, PositionUtils.IsPositionLiquidatableInfoStructOutput]
    >;
  };

  filters: {};

  estimateGas: {
    isPositionLiquidatable(
      dataStore: PromiseOrValue<string>,
      referralStorage: PromiseOrValue<string>,
      position: Position.PropsStruct,
      market: Market.PropsStruct,
      prices: MarketUtils.MarketPricesStruct,
      shouldValidateMinCollateralUsd: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isPositionLiquidatable(
      dataStore: PromiseOrValue<string>,
      referralStorage: PromiseOrValue<string>,
      position: Position.PropsStruct,
      market: Market.PropsStruct,
      prices: MarketUtils.MarketPricesStruct,
      shouldValidateMinCollateralUsd: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
