/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ISupraSValueFeedInterface extends utils.Interface {
  functions: {
    "getSvalue(uint64)": FunctionFragment;
    "getSvalues(uint64[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getSvalue" | "getSvalues"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSvalue",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSvalues",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(functionFragment: "getSvalue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSvalues", data: BytesLike): Result;

  events: {};
}

export interface ISupraSValueFeed extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISupraSValueFeedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSvalue(
      _pairIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, boolean]>;

    getSvalues(
      _pairIndexes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[string[], boolean[]]>;
  };

  getSvalue(
    _pairIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, boolean]>;

  getSvalues(
    _pairIndexes: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<[string[], boolean[]]>;

  callStatic: {
    getSvalue(
      _pairIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, boolean]>;

    getSvalues(
      _pairIndexes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[string[], boolean[]]>;
  };

  filters: {};

  estimateGas: {
    getSvalue(
      _pairIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSvalues(
      _pairIndexes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSvalue(
      _pairIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSvalues(
      _pairIndexes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
